### ISSUE TITLE
Requirement  |  Retrieving & Adding New Data

### ISSUE THREAD

**Issue by RawnieCole** [BG00924/Team-Avatar-project-2#4]
**Project Requirement**

-  Have Both GET and POST Routes for Retrieving and Adding New Data.

    -  For a Reminder on How to Create a RESTful API with GET and POST Routes for Retrieving and Adding New Data:
        -  Review Module 11: Express.js:
            -  Lesson 1: Set Up Express.js Server and GET Routes
            -  Lesson 2: Create Data Using POST Routes
        -  Along with the Rest of Module 11

**Comment by Andre835** [comment]
Thanks
